name: dijkstra_algorithm
description: A simple Dart project to demonstrate Dijkstra's algorithm.

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  collection: ^1.16.0  # Example dependency; adjust as necessary
